############# => INITIAL USER <= ###############

test_user = User.create(email: 'test@test.com', password: 'testing', photo: 'test', username: 'testing')

############# => TEXT EDITOR TAG List <= ###############

Tag.create(name: "Atom", hjs_class: "editor")
Tag.create(name: "Brackets", hjs_class: "editor")
Tag.create(name: "Sublime", hjs_class: "editor")
Tag.create(name: "Commande Line", hjs_class: "editor")

############# => CRAZY LONG CATEGORY(TAG) LIST <= ###############

# Tag.create(name: "Access logs", hjs_class: "accesslog")
# Tag.create(name: "ARM assembler",hjs_class: "arm")
# Tag.create(name: "AVR assembler", hjs_class: "arm")
# Tag.create(name: "ActionScript", hjs_class: "as")
# Tag.create(name: "Apache", hjs_class: "apache")
# Tag.create(name: "AppleScript", hjs_class: "applescript")
# Tag.create(name: "AsciiDock", hjs_class: "adoc")
Tag.create(name: "AspectJ", hjs_class: "aspecj")
# Tag.create(name: "AutoHotkey", hjs_class: "autohotkey")
# Tag.create(name: "AutoIt", hjs_class: "autoit")
# Tag.create(name: "Axapta", hjs_class: "axapta")
Tag.create(name: "Bash", hjs_class: "bash")
Tag.create(name: "zsh", hjs_class: "zsh")
# Tag.create(name: "Brainfuck", hjs_class: "bf")
Tag.create(name: "C#", hjs_class: "cs")
Tag.create(name: "C++", hjs_class: "cpp")
# Tag.create(name: "C/AL", hjs_class: "cal")
Tag.create(name: "CMake", hjs_class: "cmake")
Tag.create(name: "CSS", hjs_class: "css")
# Tag.create(name: "Cap'n Proto", hjs_class: "capnp")
# Tag.create(name: "Clojure", hjs_class: "clj")
Tag.create(name: "CoffeeScript", hjs_class: "iced")
# Tag.create(name: "Crmsh", hjs_class: "crm")
# Tag.create(name: "Crystal", hjs_class: "cr")
Tag.create(name: "D", hjs_class: "d")
# Tag.create(name: "DNS Zone file", hjs_class: "dns")
# Tag.create(name: "DOS", hjs_class: "bat")
# Tag.create(name: "Dart", hjs_class: "dart")
# Tag.create(name: "Delphi", hjs_class: "delphi")
# Tag.create(name: "Diff", hjs_class: "diff")
Tag.create(name: "Django", hjs_class: "django")
Tag.create(name: "Dockerfile", hjs_class: "docker")
# Tag.create(name: "Dust", hjs_class: "dust")
# Tag.create(name: "Elixir", hjs_class: "elixir")
# Tag.create(name: "Elm", hjs_class: "elm")
Tag.create(name: "Erlang", hjs_class: "erl")
Tag.create(name: "F#", hjs_class: "fs")
# Tag.create(name: "FIX", hjs_class: "fix")
# Tag.create(name: "Fortran", hjs_class: "fortran")
# Tag.create(name: "G-Code", hjs_class: "nc")
# Tag.create(name: "Gams", hjs_class: "gams")
# Tag.create(name: "Gherkin", hjs_class: "gherkin")
Tag.create(name: "Go", hjs_class: "go")
# Tag.create(name: "Golo", hjs_class: "golo")
Tag.create(name: "Gradle", hjs_class: "gradle")
Tag.create(name: "Groovy", hjs_class: "groovy")
Tag.create(name: "HTML", hjs_class: "html")
	Tag.create(name: "Bootstrap", hjs_class: "html")
	Tag.create(name: "Foundation", hjs_class: "html")
Tag.create(name: "XML", hjs_class: "xml")
Tag.create(name: "RSS", hjs_class: "rss")
Tag.create(name: "Atom", hjs_class: "atom")
# Tag.create(name: "Property List", hjs_class: "plist")
Tag.create(name: "HTTP", hjs_class: "http")
Tag.create(name: "Haml", hjs_class: "haml")
Tag.create(name: "Handlebars", hjs_class: "hbs")
# Tag.create(name: "Haskell", hjs_class: "hs")
Tag.create(name: "Haxe", hjs_class: "hx")
# Tag.create(name: "Ini", hjs_class: "ini")
# Tag.create(name: "Inform7", hjs_class: "i7")
# Tag.create(name: "IRPF90", hjs_class: "irpf90")
Tag.create(name: "JSON", hjs_class: "json")
Tag.create(name: "Java", hjs_class: "java")
Tag.create(name: "JavaScript", hjs_class: "js")
	Tag.create(name: "jQuery", hjs_class: "js")
	Tag.create(name: "Angular.js", hjs_class: "js")	
	Tag.create(name: "React.js", hjs_class: "js")	
	Tag.create(name: "Knockout.js", hjs_class: "js")	
	Tag.create(name: "Backbone.js", hjs_class: "js")	
	Tag.create(name: "Ember.js", hjs_class: "js")	
	Tag.create(name: "Node.js", hjs_class: "js")	
	Tag.create(name: "Express.js", hjs_class: "js")	
	Tag.create(name: "Skel.js", hjs_class: "js")
# Tag.create(name: "Lasso", hjs_class: "lasso")
Tag.create(name: "Less", hjs_class: "less")
# Tag.create(name: "Lisp", hjs_class: "lisp")
# Tag.create(name: "LiveCode Server", hjs_class: "livecodeserver")
# Tag.create(name: "LiveScript", hjs_class: "livescript")
Tag.create(name: "Lua", hjs_class: "lua")
# Tag.create(name: "Makefile", hjs_class: "mak")
Tag.create(name: "Markdown", hjs_class: "mkdown")
# Tag.create(name: "Mathematica", hjs_class: "mma")
# Tag.create(name: "Matlab", hjs_class: "matlab")
# Tag.create(name: "Maya Embedded Language", hjs_class: "mel")
# Tag.create(name: "Mercury", hjs_class: "mercury")
# Tag.create(name: "Mizar", hjs_class: "mizar")
# Tag.create(name: "Mojolicious", hjs_class: "mojolicious")
# Tag.create(name: "Monkey", hjs_class: "monkey")
# Tag.create(name: "NSIS", hjs_class: "nsis")
# Tag.create(name: "Nginx", hjs_class: "nginx")
# Tag.create(name: "Nimrod", hjs_class: "nim")
# Tag.create(name: "Nix", hjs_class: "nix")
# Tag.create(name: "OCaml", hjs_class: "ml")
Tag.create(name: "Object C", hjs_class: "objc")
Tag.create(name: "OpenGL Shading Language", hjs_class: "glsl")
# Tag.create(name: "OpenSCAD", hjs_class: "scad")
# Tag.create(name: "Oracle Rules Language", hjs_class: "ruleslanguage")
# Tag.create(name: "Oxygene", hjs_class: "oxygene")
# Tag.create(name: "PF", hjs_class: "pf")
Tag.create(name: "PHP", hjs_class: "php")
# Tag.create(name: "Parser3", hjs_class: "parser3")
# Tag.create(name: "Perl", hjs_class: "perl")
Tag.create(name: "PowerShell", hjs_class: "powershell")
# Tag.create(name: "Processing", hjs_class: "processing")
# Tag.create(name: "Prolog", hjs_class: "prolog")
# Tag.create(name: "Protocol Buffers", hjs_class: "protobuf")
# Tag.create(name: "Puppet", hjs_class: "puppet")
Tag.create(name: "Python", hjs_class: "python")
# Tag.create(name: "Python profiler results", hjs_class: "profile")
# Tag.create(name: "Q", hjs_class: "kdb")
Tag.create(name: "R", hjs_class: "r")
# Tag.create(name: "RenderMan RIB", hjs_class: "rib")
# Tag.create(name: "RenderMan RSL", hjs_class: "rsl")
# Tag.create(name: "Roboconf", hjs_class: "graph")
Tag.create(name: "Ruby", hjs_class: "ruby")
# Tag.create(name: "Rust", hjs_class: "rust")
Tag.create(name: "SCSS/Sass", hjs_class: "scss")
Tag.create(name: "SQL", hjs_class: "sql")
# Tag.create(name: "STEP Part 21", hjs_class: "step")
Tag.create(name: "Scala", hjs_class: "scala")
# Tag.create(name: "Scheme", hjs_class: "scheme")
# Tag.create(name: "Scilab", hjs_class: "sci")
# Tag.create(name: "Smali", hjs_class: "smali")
# Tag.create(name: "Smalltalk", hjs_class: "st")
# Tag.create(name: "Stata", hjs_class: "stata")
# Tag.create(name: "Stylus", hjs_class: "stylus")
Tag.create(name: "Swift", hjs_class: "swift")
# Tag.create(name: "Tcl", hjs_class: "tcl")
# Tag.create(name: "TeX", hjs_class: "tex")
# Tag.create(name: "Thrift", hjs_class: "thrift")
# Tag.create(name: "TP", hjs_class: "tp")
# Tag.create(name: "Twig", hjs_class: "twig")
Tag.create(name: "TypeScript", hjs_class: "typescript")
Tag.create(name: "VB.Net", hjs_class: "vb")
Tag.create(name: "VBScript", hjs_class: "vbs")
# Tag.create(name: "VHDL", hjs_class: "vhdl")
# Tag.create(name: "Vala", hjs_class: "vala")
# Tag.create(name: "Verilog", hjs_class: "v")
Tag.create(name: "Vim Script", hjs_class: "vim")
# Tag.create(name: "x86 Assembly", hjs_class: "x86asm")
# Tag.create(name: "XL", hjs_class: "xl")
# Tag.create(name: "XQuery", hjs_class: "xpath")
# Tag.create(name: "Zephir", hjs_class: "zep")